"use client";

import MuxPlayer from "@mux/mux-player-react";

/**
 * Explainer video below the hero — the first step of "how it works".
 * Uses a Mux PLAYBACK ID (public). Poster/thumbnail is generated by Mux
 * automatically; click-to-play (no autoplay), and `preload="none"` so it never
 * loads video bytes until the viewer hits play (it sits below the hero's LCP).
 */
export function HowItWorksVideo({
  playbackId,
  title = "How ScopeBnB works",
}: {
  playbackId: string;
  title?: string;
}) {
  return (
    <div className="overflow-hidden rounded-[4px] bg-black ring-1 ring-hairline">
      <MuxPlayer
        playbackId={playbackId}
        streamType="on-demand"
        preload="none"
        accentColor="#6ea8fe"
        metadata={{ video_title: title }}
        className="aspect-video w-full"
      />
    </div>
  );
}
